config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only: %i[new create destroy]
  resources :users, only: %i[new create show], dependant: :destroy
  resources :events, only: %i[index new create show]
  post 'attendance', to: 'events#create_attendance'
  # delete 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_events, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attendances, foreign_key: 'attended_events_id', class_name: 'Attendance'
  has_many :attendees, through: :attendances, source: :attendee

  scope :past, ->{ where('date < ?', Time.zone.now) } 
  scope :upcoming_event, ->{ where('date >= ?', Time.zone.now) } 

  validates :date, presence: true
  validates :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', dependent: :destroy, foreign_key: 'creator_id'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendances

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def ensure_login
    redirect_to new_session_path unless logged_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def event_params
    params.require(:event).permit(:date, :details)
  end

  def user_params
    params.require(:user).permit(:name)
  end

  def attendance_params
    params.require(:attendance).permit(:attended_events_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :ensure_login, only: %i[create show]

  def index
    @event = Event.all
    @past_events = Event.past
    @upcoming_events = Event.upcoming_event
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def show
    @event = find(params[:id])
    @created_events = current_user.created_events
  end

  # A conflict? You have two show actions
  #def show
    #@attendance = current_user.attendances.find_or_initialize_by(attendance_params)

    #if @attendance.save
      #redirect_to root_path
    #else
      #render :new
    #end
  #end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_login, only: %i[destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user
      session[:user_id] = @user.id
      redirect_to events_path, notice: "Welcome #{@user.id}!"
    else
      flash.now.alert = 'Login faild'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have successfully logged out.'
    redirect_to new_user_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = find_by(params[:name])
  end

  def destroy
    session.delete(:current_user)
    flash[:notice] = 'You have successfully logged out.'

    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<main><br />
  <div>
    <h3>Up coming Events</h3><br />

    <div>
      <% @upcoming_events.each do |t| %>
        <strong>Description : </strong><%= t.details%><br /><br />
        <strong>Date : </strong><%= t.date %>
        <br />
      <% end %><br /><br />
    </div>
  </div><br /><br /><hr />

  <div>
    <h3>Past events</h3>

    <div class="jumbotron">
      <% @past_events.each do |t| %>
        <strong>Description : </strong><%= t.details%><br /><br />
        <strong>Date : </strong><%= t.date %><br /><br /><br />
      <% end %><br /><br /> 
    </div>
  </div>
</main>

app/views/events/new.html.erb
<main><br />
  <div class="container jumbotron w-50 text-center">
    <%= form_with model: @event do |form|%>
      <h2>Create Event</h2><br/><hr>
      <p class="form-group">
        <%= form.label   :date, class: 'h3' %><br />
        <%= form.date_field :date, class: 'form-control' %>
      <p><br/>
      <p class="form-group">
        <%= form.label   :details, class: 'h3' %><br />
        <%= form.text_area :details, class: 'form-control', placeholder: 'Event details' %>
      <p>
      <p>
        <%= form.submit 'Create Events', class: 'btn btn-outline-success'%>
      <p>
    <% end %>
  </div>
</main>

app/views/events/show.html.erb
<main>
  
  <div>
    <h4> Created Events </h4><br />
    <% @created_events.each do |t| %>

      <%= t.details %>
      <br/>
    <% end %>
  </div><br /><hr />

  <div>
    <h4> Attendees </h4><br />
    <% @event.attendees.each do |t| %>
      <%= t.name %>
    <% end %>
  
  </div>

</main>

app/views/header/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'PrivateEvents', events_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% flash.each do |type, message| %>
		<div class="alert alert-success"><%= message %></div>
	<% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
          <% if logged_in? %>

            <li class="nav-item">
              <%= link_to "Create event", new_event_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Log Out', session_path('abc'), method: :delete, class: "nav-link" %>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'sign in', root_path, class: "nav-link" %>
          </li>
        
          <%= link_to "Create account", new_user_path, class: "nav-link" %>
       <% end %>
        <li class="nav-item">
       
        </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header/header'%>
    <div class="container">

      <%= yield %>
    </div>

  </body>
</html>

app/views/users/new.html.erb
<main>
  <h1 class="h3" >Create new user <h1><br />
  <div class="container jumbotron text-center w-50">
    <%= form_with model: @user do |form| %>
       <% if @user.errors.any? %>
        <div class="alert alert-danger">
         <% @user.errors.full_messages.each do |messages|%>
          <div><%= messages %></div>
         <% end %>
        </div>
      <% end %>

      <p>
        <%= form.label :name %>
      </p>
      <p>
        <%= form.text_field :name, class: 'form-control'%>
      </p>
      <p>
        <%= form.submit 'Create account', class: 'btn btn-outline-success'%>
      </p>
    <% end %>
  <div> 
<%= link_to 'Login', new_session_path, class: 'btn bg-primary text-white'%>
</main>

app/views/users/show.html.erb
<main>
  <h2>
    <%= @user.name%>
  </h2>

  <div class="container">
    <div>
      <h3>Events created by you</h3>
      <%= render %>
    </div>

    <div>
      <h3>Previously attended events by you</h3>
    </div>

    <div>
      <h3>Upcoming events for you</h3>
    </div>
  </div>
</main>